services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=timelygpt
      - POSTGRES_PASSWORD=4958timelygpt
      - LANG=ko_KR.UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command:
      bash -c "
        apt-get update &&
        apt-get install -y locales &&
        sed -i -e 's/# ko_KR.UTF-8 UTF-8/ko_KR.UTF-8 UTF-8/' /etc/locale.gen &&
        locale-gen &&
        update-locale LANG=ko_KR.UTF-8 &&
        docker-entrypoint.sh postgres"


  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma:/chroma/data

volumes:
  chroma:
  postgres:
